/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.mayo.bsi.semistructuredir.cdm.compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COLON = 8;
  /** RegularExpression Id. */
  int CARAT = 9;
  /** RegularExpression Id. */
  int ARR_DELIMITER = 10;
  /** RegularExpression Id. */
  int RANGE_OPEN = 11;
  /** RegularExpression Id. */
  int ARR_OPEN = 12;
  /** RegularExpression Id. */
  int RANGE_CLOSE = 13;
  /** RegularExpression Id. */
  int TYPE_DECL = 14;
  /** RegularExpression Id. */
  int STRLIT = 15;
  /** RegularExpression Id. */
  int REQUIRED = 16;
  /** RegularExpression Id. */
  int FILTERED = 17;
  /** RegularExpression Id. */
  int NEGATE = 18;
  /** RegularExpression Id. */
  int SIMPSTRLIT = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/\"",
    "\"\\n\"",
    "<token of kind 7>",
    "\":\"",
    "\"^\"",
    "\",\"",
    "<RANGE_OPEN>",
    "<ARR_OPEN>",
    "<RANGE_CLOSE>",
    "\"type:\"",
    "<STRLIT>",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "<SIMPSTRLIT>",
  };

}
